#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# When querying Nginx at its root / with a GET request
# using curl, it must return a page that contains the string Hello World!

sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
