#!/usr/bin/env bash
# Nginx installation from listening on port 80
# Delete the existing ../sites-enabled/default and replace it with a copy of
# ../sites-available/default. Do that by creating a symbolic link
# The flag -s creates a symbolic link, -f deletes the existing file and replaces it
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
